# Generated by Django 3.2.9 on 2021-11-26 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notepad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блокнота')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец блокнота')),
            ],
            options={
                'verbose_name': 'Блокнот',
                'verbose_name_plural': 'Блокноты',
            },
        ),
        migrations.CreateModel(
            name='PageForNotepad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('page_text', models.TextField(verbose_name='Текст страницы')),
                ('notepad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Page', to='notepad.notepad', verbose_name='Блокнот')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
