# Generated by Django 3.2.9 on 2021-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0002_auto_20211126_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
