# Generated by Django 3.2.9 on 2021-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepad',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
